coreConfig:
  - data_points: 5
    filter_intro: These filters affect all charts below.
    footnote: Configurations were loaded from a local file.
    intro:
    source_data_label: Source Data
    source_system_label: Source System
    title: Indicator Explorer
    indicator_id_column: questionid
    location_id_column: locationabbr
    # breakout_category_id_column: breakoutcategoryid
    breakout_category_id_column: stratificationcategoryid1
    breakout_id_column: stratificationid1
    breakout_label_column: stratification1
filterConfig:
  # There must be at least one filter with 'value_column' set to 'questionid'
  # as there are several key visualization configurations based on what indicator is selected.
  - default_value: CVD1_5
  # - default_value: AL002
    group_by_id: topicid
    group_by: topic
    label: Select an indicator
    label_column: question
    sort: '1'
    value_column: questionid
  - default_value: US
    label: Select a state
    label_column: locationdesc
    sort: '2'
    value_column: locationabbr
  - default_value: OVERALL
  # - default_value: GPOVER
    label: Select a break out category
    sort: '3'
    label_column: stratificationcategory1
    value_column: stratificationcategoryid1
    # label_column: break_out_category
    # value_column: breakoutcategoryid
chartConfig:
  - data: trend
    footnote:
    published: true
    indicator: default
    sort: '1'
    title: Trend
    type: line
  - data: latest
    footnote:
    published: true
    indicator: default
    sort: '2'
    title: Latest
    type: column
  - footnote:
    published: true
    indicator: default
    sort: '3'
    title: Map
    type: map
  - data: latest
    footnote:
    published: true
    indicator: default
    sort: '4'
    title: This should not load
    type: line
  - footnote:
    published: true
    indicator: PHY001
    sort: '1'
    title: Pie
    type: pie
  - data: latest
    footnote:
    published: true
    indicator: PHY001
    sort: '2'
    title: Latest
    type: bar
  - footnote:
    published: true
    indicator: MHL002
    sort: '1'
    title: Map
    type: map
dataSourcesConfig:
  - data_label: HRQOL
    data_link: https://chronicdata.cdc.gov/d/xuxn-8kju
    questionid: AL002
    source_label: BRFSS
    source_link: http://www.cdc.gov/brfss/
  - questionid: MHL002
    source_label: CDC
    source_link: http://www.cdc.gov/
  - data_label: Configurable Data Link
    data_link: http://www.socrata.com/
    questionid: PHY001
